name: Security Code Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  SCS:
     runs-on: windows-latest
     steps:     
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1.0.5
      - uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@master

      - name: Build
        run: |
          nuget restore
          msbuild
        
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@master
        
      - name: Upload sarif	
        uses: github/codeql-action/upload-sarif@v1
